In [1]:
try:
    spark.stop()
except Exception as e:
    print("Spark was already stopped or unavailable:", e)

Spark was already stopped or unavailable: name 'spark' is not defined

In [2]:
#Spark initialization cell
# tells spark to run locally on mac, use all CPU cores, call this investigation "HealthcareInvestigation"
from pyspark.sql import SparkSession

spark = (
    SparkSession.builder
    .appName("HealthcareInvestigation")
    .master("local[2]")
    .config("spark.driver.host", "127.0.0.1")
    .config("spark.driver.bindAddress", "127.0.0.1")
    .config("spark.ui.enabled", "false")
    .config("spark.driver.memory", "2g")
    .config("spark.executor.memory", "2g")
    .getOrCreate()
)

spark.sparkContext.setLogLevel("WARN")

print("Spark version:", spark.version)

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/10/05 08:31:50 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

Spark version: 4.0.4

In [3]:
#read beneficiary data
#tells spark to go to data/raw/beneficiary, read this csv, first row as col type, inferdata type, create a dataframe (distributed table spark can work with)
beneficiary_path = "../data/raw/beneficiary/DE1_0_2008_Beneficiary_Summary_File_Sample_2.csv"

beneficiary_df = (
    spark.read
    .option("header", True)
    .option("inferSchema", True)
    .csv(beneficiary_path)
)

beneficiary_df.printSchema()

root
 |-- DESYNPUF_ID: string (nullable = true)
 |-- BENE_BIRTH_DT: integer (nullable = true)
 |-- BENE_DEATH_DT: integer (nullable = true)
 |-- BENE_SEX_IDENT_CD: integer (nullable = true)
 |-- BENE_RACE_CD: integer (nullable = true)
 |-- BENE_ESRD_IND: string (nullable = true)
 |-- SP_STATE_CODE: integer (nullable = true)
 |-- BENE_COUNTY_CD: integer (nullable = true)
 |-- BENE_HI_CVRAGE_TOT_MONS: integer (nullable = true)
 |-- BENE_SMI_CVRAGE_TOT_MONS: integer (nullable = true)
 |-- BENE_HMO_CVRAGE_TOT_MONS: integer (nullable = true)
 |-- PLAN_CVRG_MOS_NUM: integer (nullable = true)
 |-- SP_ALZHDMTA: integer (nullable = true)
 |-- SP_CHF: integer (nullable = true)
 |-- SP_CHRNKIDN: integer (nullable = true)
 |-- SP_CNCR: integer (nullable = true)
 |-- SP_COPD: integer (nullable = true)
 |-- SP_DEPRESSN: integer (nullable = true)
 |-- SP_DIABETES: integer (nullable = true)
 |-- SP_ISCHMCHT: integer (nullable = true)
 |-- SP_OSTEOPRS: integer (nullable = true)
 |-- SP_RA_OA: integer (nullable = true)
 |-- SP_STRKETIA: integer (nullable = true)
 |-- MEDREIMB_IP: double (nullable = true)
 |-- BENRES_IP: double (nullable = true)
 |-- PPPYMT_IP: double (nullable = true)
 |-- MEDREIMB_OP: double (nullable = true)
 |-- BENRES_OP: double (nullable = true)
 |-- PPPYMT_OP: double (nullable = true)
 |-- MEDREIMB_CAR: double (nullable = true)
 |-- BENRES_CAR: double (nullable = true)
 |-- PPPYMT_CAR: double (nullable = true)

In [4]:
# show first 5 beneficiaries
#DESYNPUF_ID → beneficiary identifier
beneficiary_df.show(5, truncate=False)

+----------------+-------------+-------------+-----------------+------------+-------------+-------------+--------------+-----------------------+------------------------+------------------------+-----------------+-----------+------+-----------+-------+-------+-----------+-----------+-----------+-----------+--------+-----------+-----------+---------+---------+-----------+---------+---------+------------+----------+----------+
|DESYNPUF_ID     |BENE_BIRTH_DT|BENE_DEATH_DT|BENE_SEX_IDENT_CD|BENE_RACE_CD|BENE_ESRD_IND|SP_STATE_CODE|BENE_COUNTY_CD|BENE_HI_CVRAGE_TOT_MONS|BENE_SMI_CVRAGE_TOT_MONS|BENE_HMO_CVRAGE_TOT_MONS|PLAN_CVRG_MOS_NUM|SP_ALZHDMTA|SP_CHF|SP_CHRNKIDN|SP_CNCR|SP_COPD|SP_DEPRESSN|SP_DIABETES|SP_ISCHMCHT|SP_OSTEOPRS|SP_RA_OA|SP_STRKETIA|MEDREIMB_IP|BENRES_IP|PPPYMT_IP|MEDREIMB_OP|BENRES_OP|PPPYMT_OP|MEDREIMB_CAR|BENRES_CAR|PPPYMT_CAR|
+----------------+-------------+-------------+-----------------+------------+-------------+-------------+--------------+-----------------------+------------------------+------------------------+-----------------+-----------+------+-----------+-------+-------+-----------+-----------+-----------+-----------+--------+-----------+-----------+---------+---------+-----------+---------+---------+------------+----------+----------+
|00000B48BCF4AD29|19230901     |NULL         |2                |5           |0            |10           |260           |12                     |12                      |0                       |0                |1          |1     |1          |1      |2      |1          |1          |1          |1          |2       |1          |81000.0    |3072.0   |0.0      |1520.0     |80.0     |0.0      |6260.0      |1520.0    |0.0       |
|0000525AB30E4DEF|19201001     |NULL         |2                |1           |0            |31           |300           |12                     |12                      |0                       |12               |1          |1     |1          |2      |1      |2          |1          |1          |2          |2       |1          |13260.0    |2048.0   |0.0      |1760.0     |670.0    |0.0      |3830.0      |1010.0    |50.0      |
|00009C897C3D8372|19320101     |NULL         |1                |1           |Y            |7            |70            |12                     |12                      |12                      |12               |1          |1     |1          |1      |1      |1          |1          |1          |2          |1       |2          |37500.0    |4096.0   |0.0      |100.0      |160.0    |0.0      |1540.0      |280.0     |60.0      |
|0001168CE43BE51B|19340901     |NULL         |2                |1           |0            |6            |200           |12                     |12                      |0                       |0                |2          |2     |2          |2      |2      |2          |2          |2          |2          |2       |2          |0.0        |0.0      |0.0      |0.0        |0.0      |0.0      |0.0         |0.0       |0.0       |
|0002E494BC87CE10|19140701     |NULL         |1                |2           |0            |5            |200           |2                      |2                       |12                      |0                |2          |2     |2          |2      |2      |2          |2          |2          |2          |2       |2          |0.0        |0.0      |0.0      |0.0        |0.0      |0.0      |0.0         |0.0       |0.0       |
+----------------+-------------+-------------+-----------------+------------+-------------+-------------+--------------+-----------------------+------------------------+------------------------+-----------------+-----------+------+-----------+-------+-------+-----------+-----------+-----------+-----------+--------+-----------+-----------+---------+---------+-----------+---------+---------+------------+----------+----------+
only showing top 5 rows

26/10/05 08:31:53 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

In [5]:
#sanity check: number or rows and unique beneficiaries
print("Total rows:", beneficiary_df.count())
print("Unique beneficiaries:", beneficiary_df.select("DESYNPUF_ID").distinct().count())

Total rows: 116395
Unique beneficiaries: 116395

In [6]:
#shows cols for the first 10 beneficiaries
beneficiary_df.select(
    "DESYNPUF_ID",
    "BENE_BIRTH_DT",
    "BENE_SEX_IDENT_CD",
    "SP_DIABETES",
    "SP_CHF",
    "MEDREIMB_CAR"
).show(10)

+----------------+-------------+-----------------+-----------+------+------------+
|     DESYNPUF_ID|BENE_BIRTH_DT|BENE_SEX_IDENT_CD|SP_DIABETES|SP_CHF|MEDREIMB_CAR|
+----------------+-------------+-----------------+-----------+------+------------+
|00000B48BCF4AD29|     19230901|                2|          1|     1|      6260.0|
|0000525AB30E4DEF|     19201001|                2|          1|     1|      3830.0|
|00009C897C3D8372|     19320101|                1|          1|     1|      1540.0|
|0001168CE43BE51B|     19340901|                2|          2|     2|         0.0|
|0002E494BC87CE10|     19140701|                1|          2|     2|         0.0|
|0002EC0BCA99CACF|     19421201|                1|          2|     2|         0.0|
|0002FABBFD6D1C5C|     19240701|                2|          1|     1|      1140.0|
|000364233C3E3682|     19351201|                1|          2|     1|      1410.0|
|000433285C8D2349|     19270901|                2|          2|     2|      1740.0|
|0004B213C9EA58EC|     19421101|                2|          2|     2|         0.0|
+----------------+-------------+-----------------+-----------+------+------------+
only showing top 10 rows

In [7]:
carrier_path = "../data/raw/carrier/DE1_0_2008_to_2010_Carrier_Claims_Sample_2A.csv"

carrier_df = (
    spark.read
    .option("header", True)
    .option("inferSchema", True)
    .csv(carrier_path)
)

carrier_df.printSchema()

root
 |-- DESYNPUF_ID: string (nullable = true)
 |-- CLM_ID: long (nullable = true)
 |-- CLM_FROM_DT: integer (nullable = true)
 |-- CLM_THRU_DT: integer (nullable = true)
 |-- ICD9_DGNS_CD_1: string (nullable = true)
 |-- ICD9_DGNS_CD_2: string (nullable = true)
 |-- ICD9_DGNS_CD_3: string (nullable = true)
 |-- ICD9_DGNS_CD_4: string (nullable = true)
 |-- ICD9_DGNS_CD_5: string (nullable = true)
 |-- ICD9_DGNS_CD_6: string (nullable = true)
 |-- ICD9_DGNS_CD_7: string (nullable = true)
 |-- ICD9_DGNS_CD_8: string (nullable = true)
 |-- PRF_PHYSN_NPI_1: long (nullable = true)
 |-- PRF_PHYSN_NPI_2: long (nullable = true)
 |-- PRF_PHYSN_NPI_3: long (nullable = true)
 |-- PRF_PHYSN_NPI_4: long (nullable = true)
 |-- PRF_PHYSN_NPI_5: long (nullable = true)
 |-- PRF_PHYSN_NPI_6: long (nullable = true)
 |-- PRF_PHYSN_NPI_7: long (nullable = true)
 |-- PRF_PHYSN_NPI_8: long (nullable = true)
 |-- PRF_PHYSN_NPI_9: long (nullable = true)
 |-- PRF_PHYSN_NPI_10: long (nullable = true)
 |-- PRF_PHYSN_NPI_11: long (nullable = true)
 |-- PRF_PHYSN_NPI_12: long (nullable = true)
 |-- PRF_PHYSN_NPI_13: long (nullable = true)
 |-- TAX_NUM_1: integer (nullable = true)
 |-- TAX_NUM_2: integer (nullable = true)
 |-- TAX_NUM_3: integer (nullable = true)
 |-- TAX_NUM_4: integer (nullable = true)
 |-- TAX_NUM_5: integer (nullable = true)
 |-- TAX_NUM_6: integer (nullable = true)
 |-- TAX_NUM_7: integer (nullable = true)
 |-- TAX_NUM_8: integer (nullable = true)
 |-- TAX_NUM_9: integer (nullable = true)
 |-- TAX_NUM_10: integer (nullable = true)
 |-- TAX_NUM_11: integer (nullable = true)
 |-- TAX_NUM_12: integer (nullable = true)
 |-- TAX_NUM_13: integer (nullable = true)
 |-- HCPCS_CD_1: string (nullable = true)
 |-- HCPCS_CD_2: string (nullable = true)
 |-- HCPCS_CD_3: string (nullable = true)
 |-- HCPCS_CD_4: string (nullable = true)
 |-- HCPCS_CD_5: string (nullable = true)
 |-- HCPCS_CD_6: string (nullable = true)
 |-- HCPCS_CD_7: string (nullable = true)
 |-- HCPCS_CD_8: string (nullable = true)
 |-- HCPCS_CD_9: string (nullable = true)
 |-- HCPCS_CD_10: string (nullable = true)
 |-- HCPCS_CD_11: string (nullable = true)
 |-- HCPCS_CD_12: string (nullable = true)
 |-- HCPCS_CD_13: string (nullable = true)
 |-- LINE_NCH_PMT_AMT_1: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_2: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_3: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_4: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_5: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_6: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_7: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_8: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_9: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_10: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_11: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_12: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_13: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_1: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_2: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_3: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_4: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_5: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_6: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_7: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_8: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_9: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_10: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_11: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_12: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_13: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_1: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_2: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_3: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_4: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_5: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_6: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_7: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_8: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_9: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_10: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_11: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_12: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_13: double (nullable = true)
 |-- LINE_COINSRNC_AMT_1: double (nullable = true)
 |-- LINE_COINSRNC_AMT_2: double (nullable = true)
 |-- LINE_COINSRNC_AMT_3: double (nullable = true)
 |-- LINE_COINSRNC_AMT_4: double (nullable = true)
 |-- LINE_COINSRNC_AMT_5: double (nullable = true)
 |-- LINE_COINSRNC_AMT_6: double (nullable = true)
 |-- LINE_COINSRNC_AMT_7: double (nullable = true)
 |-- LINE_COINSRNC_AMT_8: double (nullable = true)
 |-- LINE_COINSRNC_AMT_9: double (nullable = true)
 |-- LINE_COINSRNC_AMT_10: double (nullable = true)
 |-- LINE_COINSRNC_AMT_11: double (nullable = true)
 |-- LINE_COINSRNC_AMT_12: double (nullable = true)
 |-- LINE_COINSRNC_AMT_13: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_1: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_2: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_3: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_4: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_5: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_6: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_7: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_8: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_9: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_10: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_11: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_12: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_13: double (nullable = true)
 |-- LINE_PRCSG_IND_CD_1: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_2: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_3: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_4: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_5: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_6: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_7: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_8: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_9: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_10: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_11: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_12: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_13: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_1: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_2: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_3: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_4: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_5: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_6: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_7: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_8: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_9: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_10: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_11: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_12: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_13: string (nullable = true)

In [8]:
carrier_df.printSchema()

root
 |-- DESYNPUF_ID: string (nullable = true)
 |-- CLM_ID: long (nullable = true)
 |-- CLM_FROM_DT: integer (nullable = true)
 |-- CLM_THRU_DT: integer (nullable = true)
 |-- ICD9_DGNS_CD_1: string (nullable = true)
 |-- ICD9_DGNS_CD_2: string (nullable = true)
 |-- ICD9_DGNS_CD_3: string (nullable = true)
 |-- ICD9_DGNS_CD_4: string (nullable = true)
 |-- ICD9_DGNS_CD_5: string (nullable = true)
 |-- ICD9_DGNS_CD_6: string (nullable = true)
 |-- ICD9_DGNS_CD_7: string (nullable = true)
 |-- ICD9_DGNS_CD_8: string (nullable = true)
 |-- PRF_PHYSN_NPI_1: long (nullable = true)
 |-- PRF_PHYSN_NPI_2: long (nullable = true)
 |-- PRF_PHYSN_NPI_3: long (nullable = true)
 |-- PRF_PHYSN_NPI_4: long (nullable = true)
 |-- PRF_PHYSN_NPI_5: long (nullable = true)
 |-- PRF_PHYSN_NPI_6: long (nullable = true)
 |-- PRF_PHYSN_NPI_7: long (nullable = true)
 |-- PRF_PHYSN_NPI_8: long (nullable = true)
 |-- PRF_PHYSN_NPI_9: long (nullable = true)
 |-- PRF_PHYSN_NPI_10: long (nullable = true)
 |-- PRF_PHYSN_NPI_11: long (nullable = true)
 |-- PRF_PHYSN_NPI_12: long (nullable = true)
 |-- PRF_PHYSN_NPI_13: long (nullable = true)
 |-- TAX_NUM_1: integer (nullable = true)
 |-- TAX_NUM_2: integer (nullable = true)
 |-- TAX_NUM_3: integer (nullable = true)
 |-- TAX_NUM_4: integer (nullable = true)
 |-- TAX_NUM_5: integer (nullable = true)
 |-- TAX_NUM_6: integer (nullable = true)
 |-- TAX_NUM_7: integer (nullable = true)
 |-- TAX_NUM_8: integer (nullable = true)
 |-- TAX_NUM_9: integer (nullable = true)
 |-- TAX_NUM_10: integer (nullable = true)
 |-- TAX_NUM_11: integer (nullable = true)
 |-- TAX_NUM_12: integer (nullable = true)
 |-- TAX_NUM_13: integer (nullable = true)
 |-- HCPCS_CD_1: string (nullable = true)
 |-- HCPCS_CD_2: string (nullable = true)
 |-- HCPCS_CD_3: string (nullable = true)
 |-- HCPCS_CD_4: string (nullable = true)
 |-- HCPCS_CD_5: string (nullable = true)
 |-- HCPCS_CD_6: string (nullable = true)
 |-- HCPCS_CD_7: string (nullable = true)
 |-- HCPCS_CD_8: string (nullable = true)
 |-- HCPCS_CD_9: string (nullable = true)
 |-- HCPCS_CD_10: string (nullable = true)
 |-- HCPCS_CD_11: string (nullable = true)
 |-- HCPCS_CD_12: string (nullable = true)
 |-- HCPCS_CD_13: string (nullable = true)
 |-- LINE_NCH_PMT_AMT_1: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_2: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_3: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_4: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_5: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_6: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_7: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_8: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_9: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_10: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_11: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_12: double (nullable = true)
 |-- LINE_NCH_PMT_AMT_13: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_1: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_2: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_3: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_4: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_5: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_6: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_7: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_8: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_9: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_10: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_11: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_12: double (nullable = true)
 |-- LINE_BENE_PTB_DDCTBL_AMT_13: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_1: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_2: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_3: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_4: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_5: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_6: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_7: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_8: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_9: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_10: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_11: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_12: double (nullable = true)
 |-- LINE_BENE_PRMRY_PYR_PD_AMT_13: double (nullable = true)
 |-- LINE_COINSRNC_AMT_1: double (nullable = true)
 |-- LINE_COINSRNC_AMT_2: double (nullable = true)
 |-- LINE_COINSRNC_AMT_3: double (nullable = true)
 |-- LINE_COINSRNC_AMT_4: double (nullable = true)
 |-- LINE_COINSRNC_AMT_5: double (nullable = true)
 |-- LINE_COINSRNC_AMT_6: double (nullable = true)
 |-- LINE_COINSRNC_AMT_7: double (nullable = true)
 |-- LINE_COINSRNC_AMT_8: double (nullable = true)
 |-- LINE_COINSRNC_AMT_9: double (nullable = true)
 |-- LINE_COINSRNC_AMT_10: double (nullable = true)
 |-- LINE_COINSRNC_AMT_11: double (nullable = true)
 |-- LINE_COINSRNC_AMT_12: double (nullable = true)
 |-- LINE_COINSRNC_AMT_13: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_1: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_2: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_3: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_4: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_5: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_6: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_7: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_8: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_9: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_10: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_11: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_12: double (nullable = true)
 |-- LINE_ALOWD_CHRG_AMT_13: double (nullable = true)
 |-- LINE_PRCSG_IND_CD_1: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_2: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_3: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_4: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_5: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_6: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_7: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_8: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_9: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_10: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_11: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_12: string (nullable = true)
 |-- LINE_PRCSG_IND_CD_13: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_1: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_2: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_3: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_4: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_5: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_6: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_7: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_8: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_9: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_10: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_11: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_12: string (nullable = true)
 |-- LINE_ICD9_DGNS_CD_13: string (nullable = true)

In [9]:
carrier_df.limit(5).show(truncate=False)

+----------------+---------------+-----------+-----------+--------------+--------------+--------------+--------------+--------------+--------------+--------------+--------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+----------------+----------------+----------------+----------------+---------+---------+---------+---------+---------+---------+---------+---------+---------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-----------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+-------------------+-------------------+-------------------+-------------------+--------------------------+--------------------------+--------------------------+--------------------------+--------------------------+--------------------------+--------------------------+--------------------------+--------------------------+---------------------------+---------------------------+---------------------------+---------------------------+----------------------------+----------------------------+----------------------------+----------------------------+----------------------------+----------------------------+----------------------------+----------------------------+----------------------------+-----------------------------+-----------------------------+-----------------------------+-----------------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+--------------------+--------------------+---------------------+---------------------+---------------------+---------------------+---------------------+---------------------+---------------------+---------------------+---------------------+----------------------+----------------------+----------------------+----------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+--------------------+--------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+--------------------+--------------------+
|DESYNPUF_ID     |CLM_ID         |CLM_FROM_DT|CLM_THRU_DT|ICD9_DGNS_CD_1|ICD9_DGNS_CD_2|ICD9_DGNS_CD_3|ICD9_DGNS_CD_4|ICD9_DGNS_CD_5|ICD9_DGNS_CD_6|ICD9_DGNS_CD_7|ICD9_DGNS_CD_8|PRF_PHYSN_NPI_1|PRF_PHYSN_NPI_2|PRF_PHYSN_NPI_3|PRF_PHYSN_NPI_4|PRF_PHYSN_NPI_5|PRF_PHYSN_NPI_6|PRF_PHYSN_NPI_7|PRF_PHYSN_NPI_8|PRF_PHYSN_NPI_9|PRF_PHYSN_NPI_10|PRF_PHYSN_NPI_11|PRF_PHYSN_NPI_12|PRF_PHYSN_NPI_13|TAX_NUM_1|TAX_NUM_2|TAX_NUM_3|TAX_NUM_4|TAX_NUM_5|TAX_NUM_6|TAX_NUM_7|TAX_NUM_8|TAX_NUM_9|TAX_NUM_10|TAX_NUM_11|TAX_NUM_12|TAX_NUM_13|HCPCS_CD_1|HCPCS_CD_2|HCPCS_CD_3|HCPCS_CD_4|HCPCS_CD_5|HCPCS_CD_6|HCPCS_CD_7|HCPCS_CD_8|HCPCS_CD_9|HCPCS_CD_10|HCPCS_CD_11|HCPCS_CD_12|HCPCS_CD_13|LINE_NCH_PMT_AMT_1|LINE_NCH_PMT_AMT_2|LINE_NCH_PMT_AMT_3|LINE_NCH_PMT_AMT_4|LINE_NCH_PMT_AMT_5|LINE_NCH_PMT_AMT_6|LINE_NCH_PMT_AMT_7|LINE_NCH_PMT_AMT_8|LINE_NCH_PMT_AMT_9|LINE_NCH_PMT_AMT_10|LINE_NCH_PMT_AMT_11|LINE_NCH_PMT_AMT_12|LINE_NCH_PMT_AMT_13|LINE_BENE_PTB_DDCTBL_AMT_1|LINE_BENE_PTB_DDCTBL_AMT_2|LINE_BENE_PTB_DDCTBL_AMT_3|LINE_BENE_PTB_DDCTBL_AMT_4|LINE_BENE_PTB_DDCTBL_AMT_5|LINE_BENE_PTB_DDCTBL_AMT_6|LINE_BENE_PTB_DDCTBL_AMT_7|LINE_BENE_PTB_DDCTBL_AMT_8|LINE_BENE_PTB_DDCTBL_AMT_9|LINE_BENE_PTB_DDCTBL_AMT_10|LINE_BENE_PTB_DDCTBL_AMT_11|LINE_BENE_PTB_DDCTBL_AMT_12|LINE_BENE_PTB_DDCTBL_AMT_13|LINE_BENE_PRMRY_PYR_PD_AMT_1|LINE_BENE_PRMRY_PYR_PD_AMT_2|LINE_BENE_PRMRY_PYR_PD_AMT_3|LINE_BENE_PRMRY_PYR_PD_AMT_4|LINE_BENE_PRMRY_PYR_PD_AMT_5|LINE_BENE_PRMRY_PYR_PD_AMT_6|LINE_BENE_PRMRY_PYR_PD_AMT_7|LINE_BENE_PRMRY_PYR_PD_AMT_8|LINE_BENE_PRMRY_PYR_PD_AMT_9|LINE_BENE_PRMRY_PYR_PD_AMT_10|LINE_BENE_PRMRY_PYR_PD_AMT_11|LINE_BENE_PRMRY_PYR_PD_AMT_12|LINE_BENE_PRMRY_PYR_PD_AMT_13|LINE_COINSRNC_AMT_1|LINE_COINSRNC_AMT_2|LINE_COINSRNC_AMT_3|LINE_COINSRNC_AMT_4|LINE_COINSRNC_AMT_5|LINE_COINSRNC_AMT_6|LINE_COINSRNC_AMT_7|LINE_COINSRNC_AMT_8|LINE_COINSRNC_AMT_9|LINE_COINSRNC_AMT_10|LINE_COINSRNC_AMT_11|LINE_COINSRNC_AMT_12|LINE_COINSRNC_AMT_13|LINE_ALOWD_CHRG_AMT_1|LINE_ALOWD_CHRG_AMT_2|LINE_ALOWD_CHRG_AMT_3|LINE_ALOWD_CHRG_AMT_4|LINE_ALOWD_CHRG_AMT_5|LINE_ALOWD_CHRG_AMT_6|LINE_ALOWD_CHRG_AMT_7|LINE_ALOWD_CHRG_AMT_8|LINE_ALOWD_CHRG_AMT_9|LINE_ALOWD_CHRG_AMT_10|LINE_ALOWD_CHRG_AMT_11|LINE_ALOWD_CHRG_AMT_12|LINE_ALOWD_CHRG_AMT_13|LINE_PRCSG_IND_CD_1|LINE_PRCSG_IND_CD_2|LINE_PRCSG_IND_CD_3|LINE_PRCSG_IND_CD_4|LINE_PRCSG_IND_CD_5|LINE_PRCSG_IND_CD_6|LINE_PRCSG_IND_CD_7|LINE_PRCSG_IND_CD_8|LINE_PRCSG_IND_CD_9|LINE_PRCSG_IND_CD_10|LINE_PRCSG_IND_CD_11|LINE_PRCSG_IND_CD_12|LINE_PRCSG_IND_CD_13|LINE_ICD9_DGNS_CD_1|LINE_ICD9_DGNS_CD_2|LINE_ICD9_DGNS_CD_3|LINE_ICD9_DGNS_CD_4|LINE_ICD9_DGNS_CD_5|LINE_ICD9_DGNS_CD_6|LINE_ICD9_DGNS_CD_7|LINE_ICD9_DGNS_CD_8|LINE_ICD9_DGNS_CD_9|LINE_ICD9_DGNS_CD_10|LINE_ICD9_DGNS_CD_11|LINE_ICD9_DGNS_CD_12|LINE_ICD9_DGNS_CD_13|
+----------------+---------------+-----------+-----------+--------------+--------------+--------------+--------------+--------------+--------------+--------------+--------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+----------------+----------------+----------------+----------------+---------+---------+---------+---------+---------+---------+---------+---------+---------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+-----------+-----------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+------------------+-------------------+-------------------+-------------------+-------------------+--------------------------+--------------------------+--------------------------+--------------------------+--------------------------+--------------------------+--------------------------+--------------------------+--------------------------+---------------------------+---------------------------+---------------------------+---------------------------+----------------------------+----------------------------+----------------------------+----------------------------+----------------------------+----------------------------+----------------------------+----------------------------+----------------------------+-----------------------------+-----------------------------+-----------------------------+-----------------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+--------------------+--------------------+---------------------+---------------------+---------------------+---------------------+---------------------+---------------------+---------------------+---------------------+---------------------+----------------------+----------------------+----------------------+----------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+--------------------+--------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+--------------------+--------------------+--------------------+--------------------+
|00000B48BCF4AD29|737133358637027|20080216   |20080216   |7061          |70211         |NULL          |NULL          |NULL          |NULL          |NULL          |NULL          |674382001      |674382001      |NULL           |NULL           |NULL           |NULL           |NULL           |NULL           |NULL           |NULL            |NULL            |NULL            |NULL            |331626909|331626909|NULL     |NULL     |NULL     |NULL     |NULL     |NULL     |NULL     |NULL      |NULL      |NULL      |NULL      |99213     |99202     |NULL      |NULL      |NULL      |NULL      |NULL      |NULL      |NULL      |NULL       |NULL       |NULL       |NULL       |70.0              |30.0              |0.0               |0.0               |0.0               |0.0               |0.0               |0.0               |0.0               |0.0                |0.0                |0.0                |0.0                |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                        |0.0                        |0.0                        |0.0                        |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                          |0.0                          |0.0                          |0.0                          |20.0               |10.0               |0.0                |0.0                |0.0                |0.0                |0.0                |0.0                |0.0                |0.0                 |0.0                 |0.0                 |0.0                 |110.0                |40.0                 |0.0                  |0.0                  |0.0                  |0.0                  |0.0                  |0.0                  |0.0                  |0.0                   |0.0                   |0.0                   |0.0                   |A                  |A                  |NULL               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL                |NULL                |NULL                |NULL                |7020               |4541               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL                |NULL                |NULL                |NULL                |
|00000B48BCF4AD29|737783362300937|20080219   |20080219   |9561          |71945         |NULL          |NULL          |NULL          |NULL          |NULL          |NULL          |9798189321     |9798189321     |NULL           |NULL           |NULL           |NULL           |NULL           |NULL           |NULL           |NULL            |NULL            |NULL            |NULL            |711943094|711943094|NULL     |NULL     |NULL     |NULL     |NULL     |NULL     |NULL     |NULL      |NULL      |NULL      |NULL      |73550     |A0398     |NULL      |NULL      |NULL      |NULL      |NULL      |NULL      |NULL      |NULL       |NULL       |NULL       |NULL       |280.0             |20.0              |0.0               |0.0               |0.0               |0.0               |0.0               |0.0               |0.0               |0.0                |0.0                |0.0                |0.0                |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                        |0.0                        |0.0                        |0.0                        |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                          |0.0                          |0.0                          |0.0                          |80.0               |0.0                |0.0                |0.0                |0.0                |0.0                |0.0                |0.0                |0.0                |0.0                 |0.0                 |0.0                 |0.0                 |390.0                |20.0                 |0.0                  |0.0                  |0.0                  |0.0                  |0.0                  |0.0                  |0.0                  |0.0                   |0.0                   |0.0                   |0.0                   |A                  |A                  |NULL               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL                |NULL                |NULL                |NULL                |9597               |9597               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL                |NULL                |NULL                |NULL                |
|00000B48BCF4AD29|737513360019665|20080220   |20080220   |8241          |27651         |NULL          |NULL          |NULL          |NULL          |NULL          |NULL          |1064235140     |1064235140     |NULL           |NULL           |NULL           |NULL           |NULL           |NULL           |NULL           |NULL            |NULL            |NULL            |NULL            |640295091|640295091|NULL     |NULL     |NULL     |NULL     |NULL     |NULL     |NULL     |NULL      |NULL      |NULL      |NULL      |99214     |NULL      |NULL      |NULL      |NULL      |NULL      |NULL      |NULL      |NULL      |NULL       |NULL       |NULL       |NULL       |150.0             |460.0             |0.0               |0.0               |0.0               |0.0               |0.0               |0.0               |0.0               |0.0                |0.0                |0.0                |0.0                |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                        |0.0                        |0.0                        |0.0                        |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                          |0.0                          |0.0                          |0.0                          |180.0              |60.0               |0.0                |0.0                |0.0                |0.0                |0.0                |0.0                |0.0                |0.0                 |0.0                 |0.0                 |0.0                 |670.0                |650.0                |0.0                  |0.0                  |0.0                  |0.0                  |0.0                  |0.0                  |0.0                  |0.0                   |0.0                   |0.0                   |0.0                   |A                  |A                  |NULL               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL                |NULL                |NULL                |NULL                |82123              |8448               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL                |NULL                |NULL                |NULL                |
|00000B48BCF4AD29|737553359102154|20080223   |20080223   |V676          |V5861         |NULL          |NULL          |NULL          |NULL          |NULL          |NULL          |482348367      |NULL           |NULL           |NULL           |NULL           |NULL           |NULL           |NULL           |NULL           |NULL            |NULL            |NULL            |NULL            |515899675|NULL     |NULL     |NULL     |NULL     |NULL     |NULL     |NULL     |NULL     |NULL      |NULL      |NULL      |NULL      |80100     |NULL      |NULL      |NULL      |NULL      |NULL      |NULL      |NULL      |NULL      |NULL       |NULL       |NULL       |NULL       |110.0             |0.0               |0.0               |0.0               |0.0               |0.0               |0.0               |0.0               |0.0               |0.0                |0.0                |0.0                |0.0                |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                       |0.0                        |0.0                        |0.0                        |0.0                        |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                         |0.0                          |0.0                          |0.0                          |0.0                          |20.0               |0.0                |0.0                |0.0                |0.0                |0.0                |0.0                |0.0                |0.0                |0.0                 |0.0                 |0.0                 |0.0                 |130.0                |0.0                  |0.0                  |0.0                  |0.0                  |0.0                  |0.0                  |0.0                  |0.0                  |0.0                   |0.0                   |0.0                   |0.0                   |A                  |NULL               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL                |NULL                |NULL                |NULL                |V5883              |NULL               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL               |NULL                |NULL                |NULL                |NULL                |

In [10]:
from pyspark.sql import functions as F

claim_lines_1 = (
    carrier_df
    .select(
        "DESYNPUF_ID",
        "CLM_ID",
        "CLM_FROM_DT",
        "CLM_THRU_DT",
        F.col("PRF_PHYSN_NPI_1").alias("provider_npi"),
        F.col("HCPCS_CD_1").alias("hcpcs_code"),
        F.col("LINE_NCH_PMT_AMT_1").alias("payment_amount"),
        F.col("LINE_ALOWD_CHRG_AMT_1").alias("allowed_charge"),
        F.col("LINE_BENE_PTB_DDCTBL_AMT_1").alias("beneficiary_deductible"),
        F.col("LINE_COINSRNC_AMT_1").alias("coinsurance_amount"),
        F.col("LINE_BENE_PRMRY_PYR_PD_AMT_1").alias("primary_payer_amount"),
        F.col("LINE_ICD9_DGNS_CD_1").alias("diagnosis_code")
    )
)

claim_lines_1.show(10, truncate=False)

+----------------+---------------+-----------+-----------+------------+----------+--------------+--------------+----------------------+------------------+--------------------+--------------+
|DESYNPUF_ID     |CLM_ID         |CLM_FROM_DT|CLM_THRU_DT|provider_npi|hcpcs_code|payment_amount|allowed_charge|beneficiary_deductible|coinsurance_amount|primary_payer_amount|diagnosis_code|
+----------------+---------------+-----------+-----------+------------+----------+--------------+--------------+----------------------+------------------+--------------------+--------------+
|00000B48BCF4AD29|737133358637027|20080216   |20080216   |674382001   |99213     |70.0          |110.0         |0.0                   |20.0              |0.0                 |7020          |
|00000B48BCF4AD29|737783362300937|20080219   |20080219   |9798189321  |73550     |280.0         |390.0         |0.0                   |80.0              |0.0                 |9597          |
|00000B48BCF4AD29|737513360019665|20080220   |20080220   |1064235140  |99214     |150.0         |670.0         |0.0                   |180.0             |0.0                 |82123         |
|00000B48BCF4AD29|737553359102154|20080223   |20080223   |482348367   |80100     |110.0         |130.0         |0.0                   |20.0              |0.0                 |V5883         |
|00000B48BCF4AD29|737033360678635|20080311   |20080311   |9049301835  |76705     |30.0          |140.0         |0.0                   |30.0              |0.0                 |57420         |
|00000B48BCF4AD29|737093360154764|20080307   |20080316   |4387239033  |98941     |30.0          |0.0           |0.0                   |10.0              |0.0                 |7391          |
|00000B48BCF4AD29|737223359310755|20080322   |20080322   |7407049409  |99214     |20.0          |20.0          |0.0                   |0.0               |0.0                 |2449          |
|00000B48BCF4AD29|737603362601356|20080401   |20080401   |6358044583  |J3370     |140.0         |180.0         |0.0                   |40.0              |0.0                 |99677         |
|00000B48BCF4AD29|737603361186946|20080407   |20080407   |3795815605  |85610     |30.0          |30.0          |0.0                   |0.0               |0.0                 |42731         |
|00000B48BCF4AD29|737483360372415|20080414   |20080414   |5830939787  |99213     |10.0          |60.0          |0.0                   |0.0               |0.0                 |7242          |
+----------------+---------------+-----------+-----------+------------+----------+--------------+--------------+----------------------+------------------+--------------------+--------------+
only showing top 10 rows

In [11]:
#key normalization step, each procedure gets it's own row
from functools import reduce

claim_line_dfs = []

for i in range(1, 14):
    claim_line = carrier_df.select(
        "DESYNPUF_ID",
        "CLM_ID",
        "CLM_FROM_DT",
        "CLM_THRU_DT",
        F.col(f"PRF_PHYSN_NPI_{i}").alias("provider_npi"),
        F.col(f"HCPCS_CD_{i}").alias("hcpcs_code"),
        F.col(f"LINE_NCH_PMT_AMT_{i}").alias("payment_amount"),
        F.col(f"LINE_ALOWD_CHRG_AMT_{i}").alias("allowed_charge"),
        F.col(f"LINE_BENE_PTB_DDCTBL_AMT_{i}").alias("beneficiary_deductible"),
        F.col(f"LINE_COINSRNC_AMT_{i}").alias("coinsurance_amount"),
        F.col(f"LINE_BENE_PRMRY_PYR_PD_AMT_{i}").alias("primary_payer_amount"),
        F.col(f"LINE_ICD9_DGNS_CD_{i}").alias("diagnosis_code")
    )

    claim_line_dfs.append(claim_line)

claim_lines = reduce(
    lambda df1, df2: df1.unionByName(df2),
    claim_line_dfs
)

print("Normalized claim-line table:")
claim_lines.show(10, truncate=False)

Normalized claim-line table:
+----------------+---------------+-----------+-----------+------------+----------+--------------+--------------+----------------------+------------------+--------------------+--------------+
|DESYNPUF_ID     |CLM_ID         |CLM_FROM_DT|CLM_THRU_DT|provider_npi|hcpcs_code|payment_amount|allowed_charge|beneficiary_deductible|coinsurance_amount|primary_payer_amount|diagnosis_code|
+----------------+---------------+-----------+-----------+------------+----------+--------------+--------------+----------------------+------------------+--------------------+--------------+
|00000B48BCF4AD29|737133358637027|20080216   |20080216   |674382001   |99213     |70.0          |110.0         |0.0                   |20.0              |0.0                 |7020          |
|00000B48BCF4AD29|737783362300937|20080219   |20080219   |9798189321  |73550     |280.0         |390.0         |0.0                   |80.0              |0.0                 |9597          |
|00000B48BCF4AD29|737513360019665|20080220   |20080220   |1064235140  |99214     |150.0         |670.0         |0.0                   |180.0             |0.0                 |82123         |
|00000B48BCF4AD29|737553359102154|20080223   |20080223   |482348367   |80100     |110.0         |130.0         |0.0                   |20.0              |0.0                 |V5883         |
|00000B48BCF4AD29|737033360678635|20080311   |20080311   |9049301835  |76705     |30.0          |140.0         |0.0                   |30.0              |0.0                 |57420         |
|00000B48BCF4AD29|737093360154764|20080307   |20080316   |4387239033  |98941     |30.0          |0.0           |0.0                   |10.0              |0.0                 |7391          |
|00000B48BCF4AD29|737223359310755|20080322   |20080322   |7407049409  |99214     |20.0          |20.0          |0.0                   |0.0               |0.0                 |2449          |
|00000B48BCF4AD29|737603362601356|20080401   |20080401   |6358044583  |J3370     |140.0         |180.0         |0.0                   |40.0              |0.0                 |99677         |
|00000B48BCF4AD29|737603361186946|20080407   |20080407   |3795815605  |85610     |30.0          |30.0          |0.0                   |0.0               |0.0                 |42731         |
|00000B48BCF4AD29|737483360372415|20080414   |20080414   |5830939787  |99213     |10.0          |60.0          |0.0                   |0.0               |0.0                 |7242          |
+----------------+---------------+-----------+-----------+------------+----------+--------------+--------------+----------------------+------------------+--------------------+--------------+
only showing top 10 rows

In [12]:
#Filter empty claims, see how much table has shrunk
claim_lines = (
    claim_lines
    .filter(F.col("hcpcs_code").isNotNull())
)

claim_lines.show(10, truncate=False)

print("Total claim lines:", claim_lines.count())

+----------------+---------------+-----------+-----------+------------+----------+--------------+--------------+----------------------+------------------+--------------------+--------------+
|DESYNPUF_ID     |CLM_ID         |CLM_FROM_DT|CLM_THRU_DT|provider_npi|hcpcs_code|payment_amount|allowed_charge|beneficiary_deductible|coinsurance_amount|primary_payer_amount|diagnosis_code|
+----------------+---------------+-----------+-----------+------------+----------+--------------+--------------+----------------------+------------------+--------------------+--------------+
|00000B48BCF4AD29|737133358637027|20080216   |20080216   |674382001   |99213     |70.0          |110.0         |0.0                   |20.0              |0.0                 |7020          |
|00000B48BCF4AD29|737783362300937|20080219   |20080219   |9798189321  |73550     |280.0         |390.0         |0.0                   |80.0              |0.0                 |9597          |
|00000B48BCF4AD29|737513360019665|20080220   |20080220   |1064235140  |99214     |150.0         |670.0         |0.0                   |180.0             |0.0                 |82123         |
|00000B48BCF4AD29|737553359102154|20080223   |20080223   |482348367   |80100     |110.0         |130.0         |0.0                   |20.0              |0.0                 |V5883         |
|00000B48BCF4AD29|737033360678635|20080311   |20080311   |9049301835  |76705     |30.0          |140.0         |0.0                   |30.0              |0.0                 |57420         |
|00000B48BCF4AD29|737093360154764|20080307   |20080316   |4387239033  |98941     |30.0          |0.0           |0.0                   |10.0              |0.0                 |7391          |
|00000B48BCF4AD29|737223359310755|20080322   |20080322   |7407049409  |99214     |20.0          |20.0          |0.0                   |0.0               |0.0                 |2449          |
|00000B48BCF4AD29|737603362601356|20080401   |20080401   |6358044583  |J3370     |140.0         |180.0         |0.0                   |40.0              |0.0                 |99677         |
|00000B48BCF4AD29|737603361186946|20080407   |20080407   |3795815605  |85610     |30.0          |30.0          |0.0                   |0.0               |0.0                 |42731         |
|00000B48BCF4AD29|737483360372415|20080414   |20080414   |5830939787  |99213     |10.0          |60.0          |0.0                   |0.0               |0.0                 |7242          |
+----------------+---------------+-----------+-----------+------------+----------+--------------+--------------+----------------------+------------------+--------------------+--------------+
only showing top 10 rows

Total claim lines: 4425332

In [13]:
#saving normalized dataset to parquet
claim_lines.write.mode("overwrite").parquet(
    "../data/processed/claim_lines"
)

In [14]:
import os

print(os.path.exists("../data/processed/claim_lines"))
print(os.listdir("../data/processed/claim_lines")[:5])

True
['part-00127-0388a17f-f27d-4036-bd4c-bec2a0fa8e7a-c000.snappy.parquet', '.part-00087-0388a17f-f27d-4036-bd4c-bec2a0fa8e7a-c000.snappy.parquet.crc', 'part-00026-0388a17f-f27d-4036-bd4c-bec2a0fa8e7a-c000.snappy.parquet', '.part-00022-0388a17f-f27d-4036-bd4c-bec2a0fa8e7a-c000.snappy.parquet.crc', 'part-00052-0388a17f-f27d-4036-bd4c-bec2a0fa8e7a-c000.snappy.parquet']

In [15]:
#verify spark can read dataset back in
claim_lines_parquet = spark.read.parquet(
    "../data/processed/claim_lines"
)

claim_lines_parquet.printSchema()

claim_lines_parquet.show(5, truncate=False)

root
 |-- DESYNPUF_ID: string (nullable = true)
 |-- CLM_ID: long (nullable = true)
 |-- CLM_FROM_DT: integer (nullable = true)
 |-- CLM_THRU_DT: integer (nullable = true)
 |-- provider_npi: long (nullable = true)
 |-- hcpcs_code: string (nullable = true)
 |-- payment_amount: double (nullable = true)
 |-- allowed_charge: double (nullable = true)
 |-- beneficiary_deductible: double (nullable = true)
 |-- coinsurance_amount: double (nullable = true)
 |-- primary_payer_amount: double (nullable = true)
 |-- diagnosis_code: string (nullable = true)

+----------------+---------------+-----------+-----------+------------+----------+--------------+--------------+----------------------+------------------+--------------------+--------------+
|DESYNPUF_ID     |CLM_ID         |CLM_FROM_DT|CLM_THRU_DT|provider_npi|hcpcs_code|payment_amount|allowed_charge|beneficiary_deductible|coinsurance_amount|primary_payer_amount|diagnosis_code|
+----------------+---------------+-----------+-----------+------------+----------+--------------+--------------+----------------------+------------------+--------------------+--------------+
|52B4238ED65A0A14|737363357976870|20091005   |20091005   |590681397   |99213     |0.0           |70.0          |0.0                   |100.0             |0.0                 |7246          |
|52B4238ED65A0A14|737073361463268|20091006   |20091006   |9687485335  |72148     |130.0         |80.0          |0.0                   |40.0              |0.0                 |72210         |
|52B4238ED65A0A14|737773359885985|20091031   |20091031   |7641606213  |99214     |60.0          |90.0          |0.0                   |20.0              |0.0                 |71941         |
|52B4238ED65A0A14|737373358872872|20091110   |20091110   |346162431   |99214     |140.0         |0.0           |0.0                   |30.0              |200.0               |36252         |
|52B4238ED65A0A14|737883361291546|20091111   |20091111   |3783257810  |99242     |10.0          |10.0          |0.0                   |0.0               |0.0                 |V7281         |
+----------------+---------------+-----------+-----------+------------+----------+--------------+--------------+----------------------+------------------+--------------------+--------------+
only showing top 5 rows

In [16]:
#build provider level features, turn millions of individual claims into smaller tables were one row = on provider
provider_features = (
    claim_lines_parquet
    .groupBy("provider_npi")
    .agg(
        F.count("*").alias("total_claim_lines"),
        F.countDistinct("CLM_ID").alias("unique_claims"),
        F.countDistinct("DESYNPUF_ID").alias("unique_beneficiaries"),
        F.sum("payment_amount").alias("total_payment"),
        F.avg("payment_amount").alias("avg_payment"),
        F.sum("allowed_charge").alias("total_allowed_charge"),
        F.avg("allowed_charge").alias("avg_allowed_charge"),
        F.countDistinct("hcpcs_code").alias("unique_hcpcs")
    )
)

provider_features.show(10, truncate=False)

+------------+-----------------+-------------+--------------------+-------------+------------------+--------------------+------------------+------------+
|provider_npi|total_claim_lines|unique_claims|unique_beneficiaries|total_payment|avg_payment       |total_allowed_charge|avg_allowed_charge|unique_hcpcs|
+------------+-----------------+-------------+--------------------+-------------+------------------+--------------------+------------------+------------+
|27409610    |32               |22           |20                  |1970.0       |61.5625           |2630.0              |82.1875           |25          |
|78794905    |6                |4            |4                   |340.0        |56.666666666666664|410.0               |68.33333333333333 |6           |
|114630046   |5                |3            |3                   |80.0         |16.0              |70.0                |14.0              |5           |
|231233384   |25               |10           |10                  |1200.0       |48.0              |1760.0              |70.4              |21          |
|258707912   |27               |13           |13                  |1010.0       |37.407407407407405|1930.0              |71.48148148148148 |24          |
|265451013   |33               |17           |15                  |1280.0       |38.78787878787879 |1820.0              |55.15151515151515 |32          |
|527475155   |14               |11           |10                  |640.0        |45.714285714285715|860.0               |61.42857142857143 |14          |
|680680247   |4                |3            |3                   |280.0        |70.0              |510.0               |127.5             |3           |
|784793864   |10               |5            |3                   |480.0        |48.0              |470.0               |47.0              |10          |
|897008311   |5                |2            |2                   |90.0         |18.0              |130.0               |26.0              |5           |
+------------+-----------------+-------------+--------------------+-------------+------------------+--------------------+------------------+------------+
only showing top 10 rows

In [17]:
#monthly provider activity
from pyspark.sql import functions as F

claim_lines_with_month = (
    claim_lines_parquet
    .withColumn(
        "claim_date",
        F.to_date(
            F.col("CLM_FROM_DT").cast("string"),
            "yyyyMMdd"
        )
    )
    .withColumn(
        "claim_month",
        F.date_format("claim_date", "yyyy-MM")
    )
)

claim_lines_with_month.select(
    "CLM_FROM_DT",
    "claim_date",
    "claim_month"
).show(10)

+-----------+----------+-----------+
|CLM_FROM_DT|claim_date|claim_month|
+-----------+----------+-----------+
|   20091005|2009-10-05|    2009-10|
|   20091006|2009-10-06|    2009-10|
|   20091031|2009-10-31|    2009-10|
|   20091110|2009-11-10|    2009-11|
|   20091111|2009-11-11|    2009-11|
|   20091117|2009-11-17|    2009-11|
|   20091119|2009-11-19|    2009-11|
|   20091119|2009-11-19|    2009-11|
|   20091205|2009-12-05|    2009-12|
|   20091212|2009-12-12|    2009-12|
+-----------+----------+-----------+
only showing top 10 rows

In [18]:
#activity by provider and month
monthly_provider_activity = (
    claim_lines_with_month
    .groupBy("provider_npi", "claim_month")
    .agg(
        F.count("*").alias("monthly_claim_lines"),
        F.countDistinct("CLM_ID").alias("monthly_unique_claims"),
        F.countDistinct("DESYNPUF_ID").alias("monthly_unique_beneficiaries"),
        F.sum("payment_amount").alias("monthly_payment"),
        F.countDistinct("hcpcs_code").alias("monthly_unique_hcpcs")
    )
    .orderBy("provider_npi", "claim_month")
)

monthly_provider_activity.show(20, truncate=False)

+------------+-----------+-------------------+---------------------+----------------------------+---------------+--------------------+
|provider_npi|claim_month|monthly_claim_lines|monthly_unique_claims|monthly_unique_beneficiaries|monthly_payment|monthly_unique_hcpcs|
+------------+-----------+-------------------+---------------------+----------------------------+---------------+--------------------+
|NULL        |2008-01    |776                |362                  |354                         |22280.0        |246                 |
|NULL        |2008-02    |1023               |451                  |443                         |27260.0        |300                 |
|NULL        |2008-03    |1004               |497                  |485                         |30560.0        |316                 |
|NULL        |2008-04    |1090               |523                  |515                         |35180.0        |323                 |
|NULL        |2008-05    |1048               |474                  |465                         |30730.0        |328                 |
|NULL        |2008-06    |751                |362                  |355                         |24530.0        |259                 |
|NULL        |2008-07    |678                |332                  |329                         |22930.0        |246                 |
|NULL        |2008-08    |522                |276                  |274                         |16850.0        |225                 |
|NULL        |2008-09    |485                |242                  |242                         |17290.0        |214                 |
|NULL        |2008-10    |329                |172                  |172                         |12570.0        |166                 |
|NULL        |2008-11    |350                |162                  |158                         |15030.0        |172                 |
|NULL        |2008-12    |223                |116                  |115                         |6910.0         |125                 |
|NULL        |2009-01    |237                |109                  |108                         |8760.0         |111                 |
|NULL        |2009-02    |137                |66                   |66                          |6130.0         |86                  |
|NULL        |2009-03    |114                |61                   |60                          |5430.0         |67                  |
|NULL        |2009-04    |106                |53                   |53                          |3770.0         |67                  |
|NULL        |2009-05    |99                 |48                   |48                          |3970.0         |65                  |
|NULL        |2009-06    |53                 |32                   |31                          |2510.0         |40                  |
|NULL        |2009-07    |57                 |36                   |36                          |3960.0         |40                  |
|NULL        |2009-08    |50                 |27                   |27                          |2730.0         |37                  |
+------------+-----------+-------------------+---------------------+----------------------------+---------------+--------------------+
only showing top 20 rows

In [19]:
#missing provider Ids
provider_null_counts = (
    claim_lines_parquet
    .select(
        F.count("*").alias("total_lines"),
        F.sum(
            F.when(F.col("provider_npi").isNull(), 1).otherwise(0)
        ).alias("null_provider_lines")
    )
)

provider_null_counts.show()

provider_null_counts = provider_null_counts.withColumn(
    "null_provider_percentage",
    F.round(
        F.col("null_provider_lines") / F.col("total_lines") * 100,
        2
    )
)

provider_null_counts.show()

+-----------+-------------------+
|total_lines|null_provider_lines|
+-----------+-------------------+
|    4425332|               9421|
+-----------+-------------------+

+-----------+-------------------+------------------------+
|total_lines|null_provider_lines|null_provider_percentage|
+-----------+-------------------+------------------------+
|    4425332|               9421|                    0.21|
+-----------+-------------------+------------------------+

In [20]:
#only use identifiable providers
claim_lines_with_provider = (
    claim_lines_parquet
    .filter(F.col("provider_npi").isNotNull())
)

print("Claim lines with provider:", claim_lines_with_provider.count())

Claim lines with provider: 4415911

In [21]:
#Use filtered dataframe so null providers are removed
monthly_provider_activity = (
    claim_lines_with_provider
    .withColumn(
        "claim_date",
        F.to_date(
            F.col("CLM_FROM_DT").cast("string"),
            "yyyyMMdd"
        )
    )
    .withColumn(
        "claim_month",
        F.date_format("claim_date", "yyyy-MM")
    )
    .groupBy("provider_npi", "claim_month")
    .agg(
        F.count("*").alias("monthly_claim_lines"),
        F.countDistinct("CLM_ID").alias("monthly_unique_claims"),
        F.countDistinct("DESYNPUF_ID").alias("monthly_unique_beneficiaries"),
        F.sum("payment_amount").alias("monthly_payment"),
        F.countDistinct("hcpcs_code").alias("monthly_unique_hcpcs")
    )
    .orderBy("provider_npi", "claim_month")
)
monthly_provider_activity.show(20, truncate=False)

+------------+-----------+-------------------+---------------------+----------------------------+---------------+--------------------+
|provider_npi|claim_month|monthly_claim_lines|monthly_unique_claims|monthly_unique_beneficiaries|monthly_payment|monthly_unique_hcpcs|
+------------+-----------+-------------------+---------------------+----------------------------+---------------+--------------------+
|6594        |2008-08    |6                  |1                    |1                           |60.0           |5                   |
|6594        |2009-05    |2                  |1                    |1                           |60.0           |2                   |
|42589       |2009-01    |2                  |1                    |1                           |10.0           |2                   |
|54762       |2009-11    |2                  |1                    |1                           |100.0          |2                   |
|64648       |2008-07    |4                  |1                    |1                           |20.0           |4                   |
|64648       |2008-08    |3                  |1                    |1                           |80.0           |3                   |
|64648       |2009-01    |1                  |1                    |1                           |50.0           |1                   |
|64648       |2009-07    |1                  |1                    |1                           |550.0          |1                   |
|64648       |2009-08    |2                  |1                    |1                           |40.0           |1                   |
|64648       |2009-09    |2                  |1                    |1                           |10.0           |2                   |
|64648       |2010-10    |2                  |1                    |1                           |50.0           |2                   |
|93668       |2009-10    |1                  |1                    |1                           |50.0           |1                   |
|102408      |2010-08    |1                  |1                    |1                           |60.0           |1                   |
|102408      |2010-09    |2                  |1                    |1                           |80.0           |2                   |
|114194      |2009-04    |1                  |1                    |1                           |30.0           |1                   |
|115293      |2008-01    |1                  |1                    |1                           |70.0           |1                   |
|115293      |2010-01    |8                  |1                    |1                           |50.0           |7                   |
|115293      |2010-05    |1                  |1                    |1                           |90.0           |1                   |
|143410      |2009-07    |2                  |1                    |1                           |30.0           |1                   |
|145002      |2008-03    |1                  |1                    |1                           |0.0            |1                   |
+------------+-----------+-------------------+---------------------+----------------------------+---------------+--------------------+
only showing top 20 rows

In [22]:
provider_hcpcs_summary = (
    claim_lines_with_provider
    .groupBy("provider_npi", "hcpcs_code")
    .agg(
        F.count("*").alias("claim_lines"),
        F.countDistinct("CLM_ID").alias("unique_claims"),
        F.countDistinct("DESYNPUF_ID").alias("unique_beneficiaries"),
        F.sum("payment_amount").alias("total_payment")
    )
)

provider_hcpcs_summary.show(20, truncate=False)

provider_hcpcs_summary.write.mode("overwrite").parquet(
    "../data/processed/provider_hcpcs_summary"
)

print("Saved provider HCPCS summary.")

+------------+----------+-----------+-------------+--------------------+-------------+
|provider_npi|hcpcs_code|claim_lines|unique_claims|unique_beneficiaries|total_payment|
+------------+----------+-----------+-------------+--------------------+-------------+
|70593157    |00940     |1          |1            |1                   |60.0         |
|84070903    |99285     |1          |1            |1                   |140.0        |
|208049952   |98941     |1          |1            |1                   |50.0         |
|235073716   |11604     |1          |1            |1                   |310.0        |
|295463209   |72040     |1          |1            |1                   |20.0         |
|301654125   |36556     |1          |1            |1                   |0.0          |
|302412179   |93325     |1          |1            |1                   |0.0          |
|314210365   |G0008     |2          |1            |1                   |70.0         |
|321024610   |A0425     |1          |1            |1                   |80.0         |
|349060651   |99214     |1          |1            |1                   |60.0         |
|364160738   |85610     |2          |1            |1                   |30.0         |
|389933619   |70470     |1          |1            |1                   |40.0         |
|424578614   |99212     |1          |1            |1                   |50.0         |
|435245009   |99213     |1          |1            |1                   |10.0         |
|472271689   |84520     |1          |1            |1                   |90.0         |
|479163029   |99214     |1          |1            |1                   |30.0         |
|479815821   |90862     |30         |26           |24                  |1700.0       |
|479815821   |97001     |11         |11           |11                  |370.0        |
|522696055   |83735     |1          |1            |1                   |20.0         |
|596384611   |80061     |2          |2            |2                   |0.0          |
+------------+----------+-----------+-------------+--------------------+-------------+
only showing top 20 rows

Saved provider HCPCS summary.

In [23]:
#provider level time features (one row per provider, aggregated over time)
provider_time_features = (
    monthly_provider_activity
    .groupBy("provider_npi")
    .agg(
        F.countDistinct("claim_month").alias("active_months"),
        F.avg("monthly_claim_lines").alias("avg_monthly_claim_lines"),
        F.max("monthly_claim_lines").alias("max_monthly_claim_lines"),
        F.stddev("monthly_claim_lines").alias("std_monthly_claim_lines"),
        F.avg("monthly_payment").alias("avg_monthly_payment"),
        F.max("monthly_payment").alias("max_monthly_payment"),
        F.stddev("monthly_payment").alias("std_monthly_payment"),
        F.avg("monthly_unique_beneficiaries").alias(
            "avg_monthly_unique_beneficiaries"
        )
    )
)
provider_time_features.show(10, truncate=False)

+------------+-------------+-----------------------+-----------------------+-----------------------+-------------------+-------------------+-------------------+--------------------------------+
|provider_npi|active_months|avg_monthly_claim_lines|max_monthly_claim_lines|std_monthly_claim_lines|avg_monthly_payment|max_monthly_payment|std_monthly_payment|avg_monthly_unique_beneficiaries|
+------------+-------------+-----------------------+-----------------------+-----------------------+-------------------+-------------------+-------------------+--------------------------------+
|6357152     |1            |2.0                    |2                      |NULL                   |0.0                |0.0                |NULL               |1.0                             |
|9693229     |2            |1.0                    |1                      |0.0                    |35.0               |50.0               |21.213203435596427 |1.0                             |
|20428197    |8            |2.125                  |3                      |0.8345229603962802     |71.25              |160.0              |49.69550137731641  |1.0                             |
|22835406    |2            |1.5                    |2                      |0.7071067811865476     |50.0               |60.0               |14.142135623730951 |1.0                             |
|24466109    |2            |1.0                    |1                      |0.0                    |5.0                |10.0               |7.0710678118654755 |1.0                             |
|27409610    |14           |2.2857142857142856     |8                      |2.0164161440372537     |140.71428571428572 |600.0              |170.54051112291745 |1.5714285714285714              |
|27595721    |1            |2.0                    |2                      |NULL                   |40.0               |40.0               |NULL               |1.0                             |
|29412122    |1            |2.0                    |2                      |NULL                   |40.0               |40.0               |NULL               |1.0                             |
|34354026    |1            |7.0                    |7                      |NULL                   |390.0              |390.0              |NULL               |1.0                             |
|37757633    |9            |2.6666666666666665     |7                      |2.1213203435596424     |134.44444444444446 |710.0              |218.98122699852098 |1.3333333333333333              |
+------------+-------------+-----------------------+-----------------------+-----------------------+-------------------+-------------------+-------------------+--------------------------------+
only showing top 10 rows

In [24]:
#combine provider_features (overall provider behavior) and provider_time_features (monthly activity behavior)
provider_features_combined = (
    provider_features
    .join(
        provider_time_features,
        on="provider_npi",
        how="left"
    )
)

provider_features_combined.show(10, truncate=False)

print(
    "Number of providers:",
    provider_features_combined.select("provider_npi").distinct().count()
)

+------------+-----------------+-------------+--------------------+-------------+------------------+--------------------+------------------+------------+-------------+-----------------------+-----------------------+-----------------------+-------------------+-------------------+-------------------+--------------------------------+
|provider_npi|total_claim_lines|unique_claims|unique_beneficiaries|total_payment|avg_payment       |total_allowed_charge|avg_allowed_charge|unique_hcpcs|active_months|avg_monthly_claim_lines|max_monthly_claim_lines|std_monthly_claim_lines|avg_monthly_payment|max_monthly_payment|std_monthly_payment|avg_monthly_unique_beneficiaries|
+------------+-----------------+-------------+--------------------+-------------+------------------+--------------------+------------------+------------+-------------+-----------------------+-----------------------+-----------------------+-------------------+-------------------+-------------------+--------------------------------+
|27409610    |32               |22           |20                  |1970.0       |61.5625           |2630.0              |82.1875           |25          |14           |2.2857142857142856     |8                      |2.0164161440372537     |140.71428571428572 |600.0              |170.54051112291745 |1.5714285714285714              |
|78794905    |6                |4            |4                   |340.0        |56.666666666666664|410.0               |68.33333333333333 |6           |4            |1.5                    |2                      |0.5773502691896257     |85.0               |140.0              |47.958315233127195 |1.0                             |
|114630046   |5                |3            |3                   |80.0         |16.0              |70.0                |14.0              |5           |3            |1.6666666666666667     |2                      |0.5773502691896257     |26.666666666666668 |30.0               |5.773502691896258  |1.0                             |
|231233384   |25               |10           |10                  |1200.0       |48.0              |1760.0              |70.4              |21          |9            |2.7777777777777777     |6                      |1.7159383568311668     |133.33333333333334 |420.0              |157.95568998931313 |1.1111111111111112              |
|258707912   |27               |13           |13                  |1010.0       |37.407407407407405|1930.0              |71.48148148148148 |24          |11           |2.4545454545454546     |7                      |1.809068067466582      |91.81818181818181  |380.0              |105.33927869680728 |1.1818181818181819              |
|265451013   |33               |17           |15                  |1280.0       |38.78787878787879 |1820.0              |55.15151515151515 |32          |14           |2.357142857142857      |7                      |1.8232322463624386     |91.42857142857143  |230.0              |65.85031310680107  |1.2142857142857142              |
|527475155   |14               |11           |10                  |640.0        |45.714285714285715|860.0               |61.42857142857143 |14          |10           |1.4                    |3                      |0.6992058987801011     |64.0               |150.0              |56.60781257427674  |1.1                             |
|680680247   |4                |3            |3                   |280.0        |70.0              |510.0               |127.5             |3           |3            |1.3333333333333333     |2                      |0.5773502691896257     |93.33333333333333  |180.0              |77.67453465154028  |1.0                             |
|784793864   |10               |5            |3                   |480.0        |48.0              |470.0               |47.0              |10          |5            |2.0                    |3                      |1.0                    |96.0               |300.0              |116.31852818876277 |1.0                             |
|897008311   |5                |2            |2                   |90.0         |18.0              |130.0               |26.0              |5           |2            |2.5                    |3                      |0.7071067811865476     |45.0               |70.0               |35.35533905932738  |1.0                             |
+------------+-----------------+-------------+--------------------+-------------+------------------+--------------------+------------------+------------+-------------+-----------------------+-----------------------+-----------------------+-------------------+-------------------+-------------------+--------------------------------+
only showing top 10 rows
Number of providers: 498095

In [25]:
#feature distributions, which features are heavily skewed
provider_features_combined.select(
    "total_claim_lines",
    "unique_claims",
    "unique_beneficiaries",
    "total_payment",
    "avg_payment",
    "unique_hcpcs",
    "active_months",
    "avg_monthly_claim_lines",
    "max_monthly_claim_lines",
    "avg_monthly_payment"
).describe().show()

#Most providers are pretty small
#total paid has a huge range
#avg payment is more stable
#one provider is missing time-based feature

+-------+-----------------+------------------+--------------------+-----------------+-----------------+------------------+------------------+-----------------------+-----------------------+-------------------+
|summary|total_claim_lines|     unique_claims|unique_beneficiaries|    total_payment|      avg_payment|      unique_hcpcs|     active_months|avg_monthly_claim_lines|max_monthly_claim_lines|avg_monthly_payment|
+-------+-----------------+------------------+--------------------+-----------------+-----------------+------------------+------------------+-----------------------+-----------------------+-------------------+
|  count|           498095|            498095|              498095|           498095|           498095|            498095|            498094|                 498094|                 498094|             498094|
|   mean| 8.88451399833365| 4.740579608307653|    4.09309469077184|395.8981720354551|48.40020617088741| 6.767339563737841|3.5530120820568003|      2.017355096634359|      3.230819885403157|  89.91749303450385|
| stddev|99.09126224900976|52.906886299239694|  33.071988902781804|4414.616054583382|48.69105320666263|15.481670504425965|3.7189732397604724|     2.9416914598007575|      4.639856689349686| 153.14531409291357|
|    min|                1|                 1|                   1|              0.0|              0.0|                 1|                 1|                    1.0|                      1|                0.0|
|    max|            27650|             14939|                8748|        1229590.0|            550.0|              1791|                36|      768.0555555555555|                   1010|  34155.27777777778|
+-------+-----------------+------------------+--------------------+-----------------+-----------------+------------------+------------------+-----------------------+-----------------------+-------------------+

In [26]:
#log transformed features, highly skewed dollar and count features, using log(1+x) to avoid log(0) issues
#the log transformation compresses extreme values while preserving ordering. Prevents very large providers from dominating anomaly modeling. 
from pyspark.sql import functions as F

provider_features_model = (
    provider_features_combined
    .withColumn(
        "log_total_claim_lines",
        F.log1p("total_claim_lines")
    )
    .withColumn(
        "log_unique_claims",
        F.log1p("unique_claims")
    )
    .withColumn(
        "log_unique_beneficiaries",
        F.log1p("unique_beneficiaries")
    )
    .withColumn(
        "log_total_payment",
        F.log1p("total_payment")
    )
    .withColumn(
        "log_unique_hcpcs",
        F.log1p("unique_hcpcs")
    )
    .withColumn(
        "log_avg_monthly_claim_lines",
        F.log1p("avg_monthly_claim_lines")
    )
    .withColumn(
        "log_max_monthly_claim_lines",
        F.log1p("max_monthly_claim_lines")
    )
    .withColumn(
        "log_avg_monthly_payment",
        F.log1p("avg_monthly_payment")
    )
)

provider_features_model.select(
    "total_claim_lines",
    "log_total_claim_lines",
    "total_payment",
    "log_total_payment",
    "avg_monthly_payment",
    "log_avg_monthly_payment"
).show(10, truncate=False)

+-----------------+---------------------+-------------+------------------+-------------------+-----------------------+
|total_claim_lines|log_total_claim_lines|total_payment|log_total_payment |avg_monthly_payment|log_avg_monthly_payment|
+-----------------+---------------------+-------------+------------------+-------------------+-----------------------+
|4                |1.6094379124341003   |240.0        |5.484796933490655 |120.0              |4.795790545596741      |
|16               |2.833213344056216    |830.0        |6.7226297948554485|166.0              |5.117993812416755      |
|9                |2.302585092994046    |360.0        |5.8888779583328805|72.0               |4.290459441148391      |
|4                |1.6094379124341003   |100.0        |4.61512051684126  |33.333333333333336 |3.5361166995615263     |
|21               |3.091042453358316    |350.0        |5.860786223465865 |31.818181818181817 |3.4909826855345103     |
|3                |1.3862943611198906   |10.0         |2.3978952727983707|3.3333333333333335 |1.4663370687934272     |
|23               |3.1780538303479458   |810.0        |6.698268054115413 |73.63636363636364  |4.312627836654058      |
|10               |2.3978952727983707   |610.0        |6.415096959171596 |101.66666666666667 |4.631487494305465      |
|52               |3.970291913552122    |2150.0       |7.67368812926773  |119.44444444444444 |4.791188604663372      |
|2031             |7.616775808698373    |91260.0      |11.421478812124624|2535.0             |7.8383433155571165     |
+-----------------+---------------------+-------------+------------------+-------------------+-----------------------+
only showing top 10 rows

In [27]:
#Selecting modeling features
#Mix of: overall volume, payment behavior, service types, activity, variability

#feature dataframe using log transformed variables
model_features = provider_features_model.select(
    "provider_npi",

    # Overall activity
    "log_total_claim_lines", #claim volume
    "log_unique_claims", #distinct claims
    "log_unique_beneficiaries", #patients
    "log_unique_hcpcs", #distinct procedures

    # Payment behavior
    "log_total_payment", #total paid
    "avg_payment", #average paid per claim

    # Time-based activity
    "active_months",
    "log_avg_monthly_claim_lines",
    "log_max_monthly_claim_lines",
    "log_avg_monthly_payment",

    # Variability
    "std_monthly_claim_lines", #standard deviation of monthly claim volume
    "std_monthly_payment" #standard deviation of monthly payment
)

model_features.show(10, truncate=False)

+------------+---------------------+------------------+------------------------+------------------+------------------+------------------+-------------+---------------------------+---------------------------+-----------------------+-----------------------+-------------------+
|provider_npi|log_total_claim_lines|log_unique_claims |log_unique_beneficiaries|log_unique_hcpcs  |log_total_payment |avg_payment       |active_months|log_avg_monthly_claim_lines|log_max_monthly_claim_lines|log_avg_monthly_payment|std_monthly_claim_lines|std_monthly_payment|
+------------+---------------------+------------------+------------------------+------------------+------------------+------------------+-------------+---------------------------+---------------------------+-----------------------+-----------------------+-------------------+
|27409610    |3.4965075614664802   |3.1354942159291497|3.044522437723423       |3.258096538021482 |7.58629630715272  |61.5625           |14           |1.1895840668738362         |2.1972245773362196         |4.95381295822956       |2.0164161440372537     |170.54051112291745 |
|78794905    |1.9459101490553132   |1.6094379124341003|1.6094379124341003      |1.9459101490553132|5.831882477283517 |56.666666666666664|4            |0.9162907318741551         |1.0986122886681096         |4.454347296253507      |0.5773502691896257     |47.958315233127195 |
|114630046   |1.791759469228055    |1.3862943611198906|1.3862943611198906      |1.791759469228055 |4.394449154672439 |16.0              |3            |0.9808292530117262         |1.0986122886681096         |3.3202283191284883     |0.5773502691896257     |5.773502691896258  |
|231233384   |3.258096538021482    |2.3978952727983707|2.3978952727983707      |3.091042453358316 |7.0909098220799835|48.0              |9            |1.329135947279942          |1.9459101490553132         |4.9003242732785735     |1.7159383568311668     |157.95568998931313 |
|258707912   |3.332204510175204    |2.639057329615259 |2.639057329615259       |3.2188758248682006|6.918695219020472 |37.407407407407405|11           |1.2396908869280152         |2.0794415416798357         |4.530642545366295      |1.809068067466582      |105.33927869680728 |
|265451013   |3.5263605246161616   |2.8903717578961645|2.772588722239781       |3.4965075614664802|7.155396301896734 |38.78787878787879 |14           |1.2110902720948            |2.0794415416798357         |4.5264361454455875     |1.8232322463624386     |65.85031310680107  |
|527475155   |2.70805020110221     |2.4849066497880004|2.3978952727983707      |2.70805020110221  |6.46302945692067  |45.714285714285715|10           |0.8754687373538999         |1.3862943611198906         |4.174387269895637      |0.6992058987801011     |56.60781257427674  |
|680680247   |1.6094379124341003   |1.3862943611198906|1.3862943611198906      |1.3862943611198906|5.638354669333745 |70.0              |3            |0.8472978603872036         |1.0986122886681096         |4.546834608975128      |0.5773502691896257     |77.67453465154028  |
|784793864   |2.3978952727983707   |1.791759469228055 |1.3862943611198906      |2.3978952727983707|6.175867270105761 |48.0              |5            |1.0986122886681096         |1.3862943611198906         |4.574710978503383      |1.0                    |116.31852818876277 |
|897008311   |1.791759469228055    |1.0986122886681096|1.0986122886681096      |1.791759469228055 |4.51085950651685  |18.0              |2            |1.252762968495368          |1.3862943611198906         |3.828641396489095      |0.7071067811865476     |35.35533905932738  |
+------------+---------------------+------------------+------------------------+------------------+------------------+------------------+-------------+---------------------------+---------------------------+-----------------------+-----------------------+-------------------+
only showing top 10 rows

In [28]:
#check missing values
from pyspark.sql import functions as F

model_features.select([
    F.sum(F.col(c).isNull().cast("int")).alias(c)
    for c in model_features.columns
]).show()

#lots of missing columns in std_monthly_claim_lines and std_monthly_payment, likely because these providers only have one month of activity.

+------------+---------------------+-----------------+------------------------+----------------+-----------------+-----------+-------------+---------------------------+---------------------------+-----------------------+-----------------------+-------------------+
|provider_npi|log_total_claim_lines|log_unique_claims|log_unique_beneficiaries|log_unique_hcpcs|log_total_payment|avg_payment|active_months|log_avg_monthly_claim_lines|log_max_monthly_claim_lines|log_avg_monthly_payment|std_monthly_claim_lines|std_monthly_payment|
+------------+---------------------+-----------------+------------------------+----------------+-----------------+-----------+-------------+---------------------------+---------------------------+-----------------------+-----------------------+-------------------+
|           1|                    0|                0|                       0|               0|                0|          0|            1|                          1|                          1|                      1|                 176891|             176891|
+------------+---------------------+-----------------+------------------------+----------------+-----------------+-----------+-------------+---------------------------+---------------------------+-----------------------+-----------------------+-------------------+

In [29]:
# Standard deviation is undefined for providers with only one active month,
# so treat the lack of variation as 0.
model_features = model_features.fillna({
    "std_monthly_claim_lines": 0.0,
    "std_monthly_payment": 0.0
})

#check remaining null values
model_features.select([
    F.sum(F.col(c).isNull().cast("int")).alias(c)
    for c in model_features.columns
]).show()

#look at the one provider with null values
model_features.filter(
    F.col("active_months").isNull()
).show(truncate=False)

#check original combined table
provider_features_combined.filter(
    F.col("provider_npi").isNull()
).show(truncate=False)

+------------+---------------------+-----------------+------------------------+----------------+-----------------+-----------+-------------+---------------------------+---------------------------+-----------------------+-----------------------+-------------------+
|provider_npi|log_total_claim_lines|log_unique_claims|log_unique_beneficiaries|log_unique_hcpcs|log_total_payment|avg_payment|active_months|log_avg_monthly_claim_lines|log_max_monthly_claim_lines|log_avg_monthly_payment|std_monthly_claim_lines|std_monthly_payment|
+------------+---------------------+-----------------+------------------------+----------------+-----------------+-----------+-------------+---------------------------+---------------------------+-----------------------+-----------------------+-------------------+
|           1|                    0|                0|                       0|               0|                0|          0|            1|                          1|                          1|                      1|                      0|                  0|
+------------+---------------------+-----------------+------------------------+----------------+-----------------+-----------+-------------+---------------------------+---------------------------+-----------------------+-----------------------+-------------------+

+------------+---------------------+-----------------+------------------------+----------------+------------------+-----------------+-------------+---------------------------+---------------------------+-----------------------+-----------------------+-------------------+
|provider_npi|log_total_claim_lines|log_unique_claims|log_unique_beneficiaries|log_unique_hcpcs|log_total_payment |avg_payment      |active_months|log_avg_monthly_claim_lines|log_max_monthly_claim_lines|log_avg_monthly_payment|std_monthly_claim_lines|std_monthly_payment|
+------------+---------------------+-----------------+------------------------+----------------+------------------+-----------------+-------------+---------------------------+---------------------------+-----------------------+-----------------------+-------------------+
|NULL        |9.150802659259986    |8.424200324567073|8.317277766221235       |6.93828448401696|12.653769953351677|33.21728054346672|NULL         |NULL                       |NULL                       |NULL                   |0.0                    |0.0                |
+------------+---------------------+-----------------+------------------------+----------------+------------------+-----------------+-------------+---------------------------+---------------------------+-----------------------+-----------------------+-------------------+

+------------+-----------------+-------------+--------------------+-------------+-----------------+--------------------+------------------+------------+-------------+-----------------------+-----------------------+-----------------------+-------------------+-------------------+-------------------+--------------------------------+
|provider_npi|total_claim_lines|unique_claims|unique_beneficiaries|total_payment|avg_payment      |total_allowed_charge|avg_allowed_charge|unique_hcpcs|active_months|avg_monthly_claim_lines|max_monthly_claim_lines|std_monthly_claim_lines|avg_monthly_payment|max_monthly_payment|std_monthly_payment|avg_monthly_unique_beneficiaries|
+------------+-----------------+-------------+--------------------+-------------+-----------------+--------------------+------------------+------------+-------------+-----------------------+-----------------------+-----------------------+-------------------+-------------------+-------------------+--------------------------------+
|NULL        |9421             |4555         |4093                |312940.0     |33.21728054346672|395670.0            |41.99872624986732 |1030        |NULL         |NULL                   |NULL                   |NULL                   |NULL               |NULL               |NULL               |NULL                            |
+------------+-----------------+-------------+--------------------+-------------+-----------------+--------------------+------------------+------------+-------------+-----------------------+-----------------------+-----------------------+-------------------+-------------------+-------------------+--------------------------------+

In [30]:
#Filter out null npi provider row
model_features = model_features.filter(
    F.col("provider_npi").isNotNull()
)

# Verify no missing values remain
model_features.select([
    F.sum(F.col(c).isNull().cast("int")).alias(c)
    for c in model_features.columns
]).show()

# Verify provider count
print(
    "Number of providers:",
    model_features.select("provider_npi").distinct().count()
)

+------------+---------------------+-----------------+------------------------+----------------+-----------------+-----------+-------------+---------------------------+---------------------------+-----------------------+-----------------------+-------------------+
|provider_npi|log_total_claim_lines|log_unique_claims|log_unique_beneficiaries|log_unique_hcpcs|log_total_payment|avg_payment|active_months|log_avg_monthly_claim_lines|log_max_monthly_claim_lines|log_avg_monthly_payment|std_monthly_claim_lines|std_monthly_payment|
+------------+---------------------+-----------------+------------------------+----------------+-----------------+-----------+-------------+---------------------------+---------------------------+-----------------------+-----------------------+-------------------+
|           0|                    0|                0|                       0|               0|                0|          0|            0|                          0|                          0|                      0|                      0|                  0|
+------------+---------------------+-----------------+------------------------+----------------+-----------------+-----------+-------------+---------------------------+---------------------------+-----------------------+-----------------------+-------------------+

Number of providers: 498094

In [31]:
#feature list
feature_cols = [
    "log_total_claim_lines",
    "log_unique_claims",
    "log_unique_beneficiaries",
    "log_unique_hcpcs",
    "log_total_payment",
    "avg_payment",
    "active_months",
    "log_avg_monthly_claim_lines",
    "log_max_monthly_claim_lines",
    "log_avg_monthly_payment",
    "std_monthly_claim_lines",
    "std_monthly_payment"
]

#convert to python
model_pd = model_features.select(
    "provider_npi",
    *feature_cols
).toPandas()

model_pd.head()

#check shape
print("Rows:", len(model_pd))
print("Features:", len(feature_cols))

#498904 providers, 12 features converted to pandas

Rows: 498094
Features: 12

In [32]:
#scaling features, some features r on dif scales
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = scaler.fit_transform(
    model_pd[feature_cols]
)

print("X shape:", X.shape)

X shape: (498094, 12)

In [33]:
#fit isolation forest model- unsupervised ML model used for anomaly detection
#start by assuming 1% of providers are fraudulent, can adjust later
from sklearn.ensemble import IsolationForest

iso_forest = IsolationForest(
    n_estimators=200, #builds 200 isolation trees, more trees = better performance but slower
    contamination=0.01, #flags most unusual 1% of providers
    random_state=42, #for reproducibility
    n_jobs=-1 #use all available CPU cores for parallel processing
)

iso_forest.fit(X)

print("Model fitted successfully.")

Model fitted successfully.

In [34]:
#generate anomaly scores 
model_pd["anomaly_prediction"] = iso_forest.predict(X)
model_pd["anomaly_score"] = iso_forest.decision_function(X)
#results
model_pd.head()

#flagged providers:
print(
    model_pd["anomaly_prediction"].value_counts()
)

#inspect anomoalous providers
model_pd.sort_values(
    "anomaly_score",
    ascending=True
).head(20)

anomaly_prediction
 1    493113
-1      4981
Name: count, dtype: int64

,provider_npi,log_total_claim_lines,log_unique_claims,log_unique_beneficiaries,log_unique_hcpcs,log_total_payment,avg_payment,active_months,log_avg_monthly_claim_lines,log_max_monthly_claim_lines,log_avg_monthly_payment,std_monthly_claim_lines,std_monthly_payment,anomaly_prediction,anomaly_score
497551,9979265126,9.809342,9.187993,8.796188,7.361375,13.614228,44.922536,36,6.227744,6.552508,10.030751,151.544482,7156.817329,-1,-0.170108
177303,7132269719,9.179366,8.544614,7.661998,7.074963,13.011076,46.146070,36,5.599450,5.905362,9.427636,82.570701,4117.732578,-1,-0.170108
297860,1973668724,9.675080,9.040382,7.763021,7.297091,13.475343,44.715677,36,6.093758,6.456770,9.891873,130.859876,6348.605165,-1,-0.170108
197996,7961400834,9.453365,8.826294,8.535819,7.188413,13.275292,45.695686,36,5.872587,6.173786,9.691833,99.072412,4785.740891,-1,-0.170108
374593,5040521237,9.037890,8.390268,7.629004,7.005789,12.825334,44.148544,36,5.458521,5.805135,9.241909,77.854581,3231.932183,-1,-0.170108
413117,6585316279,9.201501,8.549273,8.278936,7.057898,12.998977,44.592877,36,5.621507,5.966147,9.415537,83.894771,4152.720279,-1,-0.170108
337345,3552796390,9.320181,8.698347,7.826842,7.158514,13.114434,44.448925,36,5.739793,6.049733,9.530986,85.947160,4448.033514,-1,-0.170108
22139,888901330,10.227417,9.611797,9.076695,7.491088,14.022192,44.469801,36,6.645163,6.918695,10.438702,221.662284,10011.419904,-1,-0.170108
272288,941734431,9.338470,8.716044,8.388223,7.100027,13.156380,45.512933,36,5.758025,6.104793,9.572929,96.838779,4952.326405,-1,-0.170108
257072,329757128,9.279307,8.657303,8.346168,7.075809,13.065287,44.082890,36,5.699049,6.089045,9.481842,94.419240,4562.760130,-1,-0.170108
71259,2866295111,9.378478,8.758098,8.446556,7.185387,13.177857,44.677092,36,5.797914,6.084499,9.594404,93.704483,4613.806085,-1,-0.170108
453446,8207899456,9.901586,9.270306,8.866158,7.401842,13.698674,44.573418,36,6.319819,6.622736,10.115195,158.336980,7633.545324,-1,-0.170108
299839,2052541087,9.636196,9.025095,8.680162,7.266827,13.446736,45.177685,36,6.054961,6.418365,9.863267,128.603068,6364.917212,-1,-0.170108
26141,1052105939,9.524567,8.888895,8.511376,7.196687,13.289302,43.155358,36,5.943601,6.350886,9.705843,113.782454,5093.049668,-1,-0.169836
175475,7058697667,8.408271,7.806289,7.473069,6.705639,12.234811,45.913451,36,4.832527,5.231109,8.651462,43.711055,2293.007227,-1,-0.169565
343638,3806728350,8.235626,7.628518,6.113682,6.648985,12.032737,44.583775,36,4.661340,5.170484,8.449426,36.924720,1648.544211,-1,-0.169565
111402,4482363487,8.056744,7.468513,6.909753,6.584791,11.856522,44.705136,36,4.484257,5.111988,8.273252,30.107690,1519.191514,-1,-0.169565
178548,7183629035,8.912877,8.274612,7.615298,6.934397,12.706002,44.400754,36,5.334060,5.697093,9.122589,67.023497,3396.466044,-1,-0.169565
137790,5546775825,8.509766,7.895436,7.754482,6.760415,12.296329,44.113261,36,4.933274,5.407172,8.712970,45.029831,2123.922902,-1,-0.169565
280239,1256684163,8.295299,7.689371,7.598399,6.646391,12.118612,45.766733,36,4.720481,5.111988,8.535284,34.920408,1638.303105,-1,-0.169565

In [35]:
#compare feature distributions for normal vs anomalous providers
model_pd.groupby("anomaly_prediction")[feature_cols].mean().T

#median comparison is often more informative for skewed data
model_pd.groupby("anomaly_prediction")[feature_cols].median().T

#results: model is finding providers that look unusual because they have much higher and variable activity

anomaly_prediction                   -1          1
log_total_claim_lines          4.189655   1.609438
log_unique_claims              3.526361   1.098612
log_unique_beneficiaries       3.258097   1.098612
log_unique_hcpcs               3.891820   1.609438
log_total_payment              8.023225   5.017280
avg_payment                   46.470078  37.500000
active_months                 21.000000   2.000000
log_avg_monthly_claim_lines    1.510592   0.998529
log_max_monthly_claim_lines    2.564949   1.098612
log_avg_monthly_payment        5.129899   4.189655
std_monthly_claim_lines        3.068945   0.500000
std_monthly_payment          201.872159  28.284271

In [36]:
import os

os.makedirs("../data/processed", exist_ok=True)

model_pd.to_parquet(
    "../data/processed/provider_anomaly_results.parquet",
    index=False
)

print("Saved anomaly results.")

import os
print(os.getcwd())

Saved anomaly results.
/Users/manyasood/Documents/healthcare-investigation/notebooks

In [37]:
#load monthly data
provider_time_features.write.mode("overwrite").parquet(
    "../data/processed/provider_time_features"
)

print("Saved monthly provider features.")

Saved monthly provider features.

In [38]:
[x for x in dir() if "month" in x.lower() or "time" in x.lower()]
[x for x in dir() if "claim" in x.lower() or "provider" in x.lower()]

['claim_line',
 'claim_line_dfs',
 'claim_lines',
 'claim_lines_1',
 'claim_lines_parquet',
 'claim_lines_with_month',
 'claim_lines_with_provider',
 'monthly_provider_activity',
 'provider_features',
 'provider_features_combined',
 'provider_features_model',
 'provider_hcpcs_summary',
 'provider_null_counts',
 'provider_time_features']

In [39]:
#to print provider monthly activity table
monthly_provider_activity.printSchema()
monthly_provider_activity.show(10)
monthly_provider_activity.columns

root
 |-- provider_npi: long (nullable = true)
 |-- claim_month: string (nullable = true)
 |-- monthly_claim_lines: long (nullable = false)
 |-- monthly_unique_claims: long (nullable = false)
 |-- monthly_unique_beneficiaries: long (nullable = false)
 |-- monthly_payment: double (nullable = true)
 |-- monthly_unique_hcpcs: long (nullable = false)

+------------+-----------+-------------------+---------------------+----------------------------+---------------+--------------------+
|provider_npi|claim_month|monthly_claim_lines|monthly_unique_claims|monthly_unique_beneficiaries|monthly_payment|monthly_unique_hcpcs|
+------------+-----------+-------------------+---------------------+----------------------------+---------------+--------------------+
|        6594|    2008-08|                  6|                    1|                           1|           60.0|                   5|
|        6594|    2009-05|                  2|                    1|                           1|           60.0|                   2|
|       42589|    2009-01|                  2|                    1|                           1|           10.0|                   2|
|       54762|    2009-11|                  2|                    1|                           1|          100.0|                   2|
|       64648|    2008-07|                  4|                    1|                           1|           20.0|                   4|
|       64648|    2008-08|                  3|                    1|                           1|           80.0|                   3|
|       64648|    2009-01|                  1|                    1|                           1|           50.0|                   1|
|       64648|    2009-07|                  1|                    1|                           1|          550.0|                   1|
|       64648|    2009-08|                  2|                    1|                           1|           40.0|                   1|
|       64648|    2009-09|                  2|                    1|                           1|           10.0|                   2|
+------------+-----------+-------------------+---------------------+----------------------------+---------------+--------------------+
only showing top 10 rows

['provider_npi',
 'claim_month',
 'monthly_claim_lines',
 'monthly_unique_claims',
 'monthly_unique_beneficiaries',
 'monthly_payment',
 'monthly_unique_hcpcs']

In [40]:
import os

os.makedirs("../data/processed", exist_ok=True)

monthly_provider_activity.write.mode("overwrite").parquet(
    "../data/processed/monthly_provider_activity"
)

print("Saved monthly provider activity.")

Saved monthly provider activity.

In [ ]:
import os

print(
    os.path.exists("../data/processed/monthly_provider_activity")
)

True

26/10/05 23:42:49 WARN HeartbeatReceiver: Removing executor driver with no recent heartbeats: 822630 ms exceeds timeout 120000 ms
26/10/05 23:42:49 WARN SparkContext: Killing executors is not supported by current scheduler.
26/10/05 23:42:57 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:132)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:131)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:700)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:699)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:739)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:141)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:216)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:76)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@127.0.0.1:52342
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:151)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:147)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:312)
	at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:176)
	at org.apache.spark.rpc.netty.NettyRpcEnv.asyncSetupEndpointRefByURI(NettyRpcEnv.scala:153)
	... 17 more
26/10/05 23:42:57 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:81)
	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:669)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1296)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:307)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1937)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:132)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:131)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:700)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:699)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:739)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:141)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:216)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:76)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:42)
	... 3 more
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@127.0.0.1:52342
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:151)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:147)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:312)
	at scala.concurrent.impl.Promise$DefaultPromise.flatMap(Promise.scala:176)
	at org.apache.spark.rpc.netty.NettyRpcEnv.asyncSetupEndpointRefByURI(NettyRpcEnv.scala:153)
	... 17 more
26/10/05 23:43:07 ERROR Inbox: Ignoring error
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:132)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:131)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:700)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:699)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:739)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:141)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:216)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:76)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@127.0.0.1:52342
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:151)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:147)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:335)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at scala.concurrent.Promise.trySuccess(Promise.scala:99)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:99)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:104)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:228)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:242)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:241)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at scala.concurrent.Promise.complete(Promise.scala:57)
	at scala.concurrent.Promise.complete$(Promise.scala:56)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
	at scala.concurrent.Promise.success(Promise.scala:91)
	at scala.concurrent.Promise.success$(Promise.scala:91)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:104)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more
26/10/05 23:43:07 WARN Executor: Issue communicating with driver in heartbeater
org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:101)
	at org.apache.spark.rpc.RpcEndpointRef.askSync(RpcEndpointRef.scala:85)
	at org.apache.spark.storage.BlockManagerMaster.registerBlockManager(BlockManagerMaster.scala:81)
	at org.apache.spark.storage.BlockManager.reregister(BlockManager.scala:669)
	at org.apache.spark.executor.Executor.reportHeartBeat(Executor.scala:1296)
	at org.apache.spark.executor.Executor.$anonfun$heartbeater$1(Executor.scala:307)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1937)
	at org.apache.spark.Heartbeater$$anon$1.run(Heartbeater.scala:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.spark.SparkException: Exception thrown in awaitResult:
	at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:53)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:342)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
	at org.apache.spark.util.RpcUtils$.makeDriverRef(RpcUtils.scala:36)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.driverEndpoint$lzycompute(BlockManagerMasterEndpoint.scala:132)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$driverEndpoint(BlockManagerMasterEndpoint.scala:131)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$lzycompute$1(BlockManagerMasterEndpoint.scala:700)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.isExecutorAlive$1(BlockManagerMasterEndpoint.scala:699)
	at org.apache.spark.storage.BlockManagerMasterEndpoint.org$apache$spark$storage$BlockManagerMasterEndpoint$$register(BlockManagerMasterEndpoint.scala:739)
	at org.apache.spark.storage.BlockManagerMasterEndpoint$$anonfun$receiveAndReply$1.applyOrElse(BlockManagerMasterEndpoint.scala:141)
	at org.apache.spark.rpc.netty.Inbox.$anonfun$process$1(Inbox.scala:104)
	at org.apache.spark.rpc.netty.Inbox.safelyCall(Inbox.scala:216)
	at org.apache.spark.rpc.netty.Inbox.process(Inbox.scala:101)
	at org.apache.spark.rpc.netty.MessageLoop.org$apache$spark$rpc$netty$MessageLoop$$receiveLoop(MessageLoop.scala:76)
	at org.apache.spark.rpc.netty.MessageLoop$$anon$1.run(MessageLoop.scala:42)
	... 3 more
Caused by: org.apache.spark.rpc.RpcEndpointNotFoundException: Cannot find endpoint: spark://CoarseGrainedScheduler@127.0.0.1:52342
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1(NettyRpcEnv.scala:151)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$asyncSetupEndpointRefByURI$1$adapted(NettyRpcEnv.scala:147)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
	at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:335)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at scala.concurrent.Promise.trySuccess(Promise.scala:99)
	at scala.concurrent.Promise.trySuccess$(Promise.scala:99)
	at scala.concurrent.impl.Promise$DefaultPromise.trySuccess(Promise.scala:104)
	at org.apache.spark.rpc.netty.NettyRpcEnv.onSuccess$1(NettyRpcEnv.scala:228)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5(NettyRpcEnv.scala:242)
	at org.apache.spark.rpc.netty.NettyRpcEnv.$anonfun$askAbortable$5$adapted(NettyRpcEnv.scala:241)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at org.apache.spark.util.ThreadUtils$$anon$1.execute(ThreadUtils.scala:99)
	at scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
	at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:278)
	at scala.concurrent.Promise.complete(Promise.scala:57)
	at scala.concurrent.Promise.complete$(Promise.scala:56)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:104)
	at scala.concurrent.Promise.success(Promise.scala:91)
	at scala.concurrent.Promise.success$(Promise.scala:91)
	at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:104)
	at org.apache.spark.rpc.netty.LocalNettyRpcCallContext.send(NettyRpcCallContext.scala:50)
	at org.apache.spark.rpc.netty.NettyRpcCallContext.reply(NettyRpcCallContext.scala:32)
	at org.apache.spark.rpc.netty.RpcEndpointVerifier$$anonfun$receiveAndReply$1.applyOrElse(RpcEndpointVerifier.scala:31)
	... 8 more
26/10/05 23:43:17 ERROR Inbox: Ignoring error